fleet:
  name: toio
  robots:
    - name: cube_0
      cube_id: N7D
      led_color: [0xFF, 0x00, 0x00]
    - name: cube_1
      cube_id: n0Q
      led_color: [0x00, 0x00, 0xFF]

toio:
  speed_max_value: 20
  speed_change_type: 3

frames:
  map: map
  robot: base_footprint
